[package]
name = "advent_2019"
version = "0.1.0"
authors = ["Zvonimir Erdelja <zvonimir.erdelja@gmail.com>"]
edition = "2018"
include = ["../data/*.txt", "**/*.rs","Cargo.toml"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
